config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/team'
  post "home/team" => 'home#team'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :common_content, :only => [:index, :team]
  
  def common_content
    # detect if on mobile browser or not
    
    
    # generate our superhero instance variables
    @super_hero_name = Faker::Superhero.name
    @super_hero_power = Faker::Superhero.power
    
    
    @random_set = rand(1..2)
    if @random_set == 1
      @random_set_pic = "set1"
    else
      @random_set_pic = "set2"
    end
    
    @corporate_job = Faker::Name.title
    @corporate_power = Faker::Company.bs
    @random_avatar = rand(1..100)
    @super_hero_avatar = Faker::Avatar.image(@random_avatar, "300x300", "png", @random_set_pic, "bg2" )
  end
  
  
  def index
  end

  def team
    @teams = "red"
    @team_number = params[:team_number].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_create_team.html.erb
            <div class="panel panel-default">
				<div class="panel-heading">
				<h3 class="panel-title gray">How Many Team Members Do You Want?</h3>
				</div>
				<div class="panel-body">
					<div class="row">
					<div class="col-md-4">
					<%= form_tag home_team_path, :method => 'POST' do %>
                       <%= select_tag(:team_number, options_for_select([
                       ['1', 1], 
                       ['2', 2],
                       ['3', 3], 
                       ['4', 4],
                       ['5', 5], 
                       ['6', 6],
                       ['7', 7], 
                       ['8', 8],
                       ['9', 9], 
                       ['10', 10],
                       ]), class: 'form-control') %>
                       
                        <br/><br/>
                      <%= submit_tag 'Build Your Team!' %>
                    <% end %>
					
					</div>
					<div class="col-md-4">
					    
					</div>
					    
					<div class="col-md-4">
						<%= render "home/side_ad_code" %>
					</div>	
					
					</div>
				</div>
				<div class="panel-footer"></div>
			</div>

app/views/home/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://superhero.JohnElder.org">SUPERHERO NAME GENERATOR</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Create Superhero", root_path %></li>
          <li><%= link_to "Create Superhero Team", home_team_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_show_team.html.erb
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title gray">Your Superhero Team...</h3>
</div>
<div class="panel-body">
	
	
	
	<% @team_number.times do %>
	    <% rand_pic = rand(1..2) %>
            <div class="row">
    	        <div class="col-md-4">
    			    <img src="<%= Faker::Avatar.image(rand(1..100), "300x300", "png", if (rand_pic == 1) then "set1" else "set2" end, "bg2" ) %>" class="hero_img">
    			</div>
    					
    		    <div class="col-md-4">
        			<h3>Superhero Name: <br/><span class="red"><%= Faker::Superhero.name %></span></h3>
        			<h3>Super Power: <br/><span class="red"><%= Faker::Superhero.power %></span></h3>
        					
        			<br/>
        					
    				<h4>Their Undercover Day Job is:<br/> <span class="corporate"><%= Faker::Name.title %></span></h4>
    				<h4>Their Corporate Superpower is:<br/> <span class="corporate"><%= Faker::Company.bs.titleize %></span></h4>
    			</div>
    			
    			<div class="col-md-4">
                	<%= render "home/side_team_ad" %>
                </div>	
	
    		</div>	
    	    <div class="row">
        	    <div class="col-md-12">
        	        <hr>
        	    </div>
    	    </div>
    		
	<% end %>
	
	</div>
	<div class="panel-footer"><%= link_to "Create New Team...", home_team_path %></div>
</div>
    

app/views/home/_top_index_ad.html.erb
<% @foo = 6 %>
<% if @foo = 7 %>

<% else %>

<div class="row">
    <div class="col-md-12">
        <center>
            <% if browser.device.mobile? %>
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Superhero Responsive -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-9933096370821149"
                         data-ad-slot="8020365924"
                         data-ad-format="auto"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
                
            <% else %>
            
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Superhero top -->
                    <ins class="adsbygoogle"
                         style="display:inline-block;width:728px;height:90px"
                         data-ad-client="ca-pub-9933096370821149"
                         data-ad-slot="4185595520"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
                
            <% end %>
            <br/>
        </center>
    </div>
</div>

<% end %>

app/views/home/_top_team_ad.html.erb
<% @foo = 6 %>
<% if @foo = 7 %>

<% else %>

<div class="row">
    <div class="col-md-12">
        <center>
            <% if browser.device.mobile? %>
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Superhero Responsive -->
                    <ins class="adsbygoogle"
                         style="display:block"
                         data-ad-client="ca-pub-9933096370821149"
                         data-ad-slot="8020365924"
                         data-ad-format="auto"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
                
            <% else %>
            
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Superhero top -->
                    <ins class="adsbygoogle"
                         style="display:inline-block;width:728px;height:90px"
                         data-ad-client="ca-pub-9933096370821149"
                         data-ad-slot="4185595520"></ins>
                    <script>
                    (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
                
            <% end %>
            <br/>
        </center>
    </div>
</div>

<% end %>

app/views/home/index.html.erb
<div class="container" >
    <%= render 'home/top_index_ad' %>
    
    <br/>

			<div class="panel panel-default">
				<div class="panel-heading">
				<h3 class="panel-title gray"><%= link_to "Click Here To Generate A New Superhero", root_path %></h3>
				</div>
				<div class="panel-body">
					<div class="row">
					<div class="col-md-4">
					    <img src="<%= @super_hero_avatar %>" class="hero_img">
					</div>
					
					<div class="col-md-4">
    					<h3>Your Superhero Name: <br/><span class="red"><%= @super_hero_name %></span></h3>
    					<h3>Your Super Power: <br/><span class="red"><%= @super_hero_power %></span></h3>
    					
    					<br/>
    					
    					
    					<h4>Your Undercover Day Job is: <br/><span class="corporate"><%= @corporate_job %></span></h4>
    					<h4>Your Corporate Superpower is: <br/><span class="corporate"><%= @corporate_power.titleize %></span></h4>
					</div>
					
					<div class="col-md-4">
						<%= render "home/side_ad_code" %>
					</div>	
					
					</div>
				</div>
				<div class="panel-footer"><%= link_to "Create A Whole Superhero Team", home_team_path %></div>
			</div>
    
    
    
    
    
    
    
</div>

app/views/home/team.html.erb
<div class="container" >
    <%= render 'home/top_team_ad' %>
    
    <br/>



        <% if @team_number < 1 %>
            <%= render 'home/create_team' %>
    
        <% else %>

			<%= render 'home/show_team' %>
    
        <% end %>
    
    
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superhero Name Generator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="Superhero Name Generator! Generate one superhero or a whole team!">
<meta property="og:site_name" content="Superhero Name Generator" />
<meta property="og:url" content="http://superhero.johnelder.org" /> 
<meta property="og:title" content="Superhero Name Generator" /> 
<meta property="og:description" content="Superhero Name Generator! Generate one superhero or a whole team!" />
<% rand_pic = rand(1..2) %>
<meta property="og:image" content="http://johnelder.org/images/superhero_img.png"  />
  
  
  <style>
    html,
		body {height:100%; background-color: #fff;  background-image: url("http://cdn.johnelder.org/superhero/stripe2.png")}
		.panel-body{margin-bottom: 30px; margin-top:20px;}
		.panel{margin-bottom: 100px;}
		h2 {color: #777777;}
		h3 {color: #777;}
		h4 {color: #bbb;}
		.gray {color: #777777;}
		.red {color: red;}
		.hero_img {padding-right:20px;}
		.corporate {color: #fba2a2};
  </style>
</head>
<body>
<%= render 'home/nav' %>
<%= yield %>

<center>Copyright &copy; <a href="http://JohnElder.org">JohnElder.org</a> - All Rights Reserved</center>
<br/><br/>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-33832930-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>